### ISSUE TITLE
Add template features

### ISSUE THREAD

**Issue by bgins** [fission-codes/rust-template#1]
A template includes many things! ✨ Here is a list of what we think should be included in this template:

- [x] [CI](https://github.com/fission-codes/rust-template/pull/3)
	- [x] Runs tests and checks  
		- Clippy checks 
	- [x] Dependabot file
	- [x] Deployment  
- [x] [Pre-commit hooks](https://github.com/fission-codes/rust-template/pull/3) (_Should not run tests_)
  - [x] Clippy  
  - [x] Check (`cargo check`), sort dependencies  
  - [x] Import ordering and granularity (uses nightly `fmt`)
  - [x] User must install an `npm` library (add note to README)
- [x] [Issue and PR templates](https://github.com/fission-codes/rust-wasm-template/pull/2)
- [x] [README](https://github.com/fission-codes/rust-template/pull/3)
	- [x] Badges  
		- Codecov  
		- Discord  
		- Discourse  
		- License
		- Others? 
- [x] [CONTRIBUTING guide](https://github.com/fission-codes/rust-template/pull/4)
	- When to discuss vs issue?  
	- Link to best practices guide  
	- Link to code of conduct  
- [x] [LICENSE](https://github.com/fission-codes/rust-template/pull/3)
- [x] [Codeowners file](https://github.com/fission-codes/rust-template/pull/3)
	- Who can deploy  
	- PRs need one review from one code owner  
	- No merge commits, everybody rebase! 🕺 
- [x] [Releases](https://github.com/fission-codes/rust-template/pull/3)
	- [x] `release-please`  
		- Runs release part of CI, publish on crates.io, npm
		- Automatically tags and creates GH release  
		- Updates `Cargo.toml` with version 
		- [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
			- Commits are tagged in the first line of the commit message  
		- Provides semantic versioning  
		- Use a GH action?   
- [x] [Nix support](https://github.com/fission-codes/rust-template/pull/3)  
  - Installs tooling and binaries outside of Rust ecosystem and/or helpful cargo packages
- [x] [`wasmpack`](https://github.com/fission-codes/rust-template/pull/3)
	- Support for libs that use Wasm in the browser for example

**Comment by zeeshanlakhani** [comment]
Added the one over here as well @bgins: https://github.com/fission-codes/rust-template/issues/1.

**Comment by zeeshanlakhani** [comment]
We can't move GH settings over via templates, but I did make signing commits default at the org level for our working groups/fission-codes.
