### ISSUE TITLE
Badges may conflict with existing packages

### ISSUE THREAD

**Issue by expede** [fission-codes/rust-template#152]
# Summary

## Problem

The autogenerated badges _may_ conflict with existing packages. See issue on Rhizome: https://github.com/RhizomeDB/rs-rhizome/issues/90

### Impact

The README can point to random other people's projects

## Solution

It may be more work than it's worth, but checking if the project name being generated is already taken on Crates and NPM is one approach. Even printing a reminder to check would be a good thing.

**Comment by zeeshanlakhani** [comment]
Yeah. The generator can't make network calls :). But, I will add it to the documentation as a check.
