### ISSUE TITLE
Take better advantage of --init flag for generating inside an already-created Rust project directory

### ISSUE THREAD

**Issue by zeeshanlakhani** [fission-codes/rust-template#17]
Would probably be good to incorporate an `is_init` ignore readme/toml/src(/main/lib) and allow for adding benches, wasm, nix pieces. 

### References

- https://cargo-generate.github.io/cargo-generate/usage.html#generating-into-current-dir
  ```
  ⚠️ NOTE: cargo-generate will not allow any existing files to be overwritten and will 
  fail to generate any files should there be any conflicts.
  ```
  Using these flags:

  ```
  {{within_cargo_project}}

  A boolean with the value true if the template is being expanded inside a Cargo project. 
  It's a simple matter of whether Cargo.toml is present in any parent folder.

  {{is_init}}

  A boolean that reflects the value of the --init parameter of cargo-generate.
  ```

- how bevy template does it: https://github.com/search?q=repo%3Ataurr%2Fbevy-template-rs%20is_init&type=code

**Comment by pinkforest** [comment]
Can test this retro on: https://github.com/fission-codes/fission-cli/issues

**Comment by zeeshanlakhani** [comment]
@pinkforest yep. That's the plan I've talked to @bgins about.

**Comment by bgins** [comment]
@pinkforest yep, that's the plan! If you have spare time and are interested in helping, PRs are welcomed. 🙂
