### ISSUE TITLE
Support specifying a repo name, distinct from the project name

### ISSUE THREAD

**Issue by QuinnWilton** [fission-codes/rust-template#30]
# Summary

The repo name, for Github, is currently chosen based on the project name. Sometimes it makes sense to prefix the repo name in some way, while leaving that prefix out of the code itself, such as in the case of `rs-wnfs` / `wnfs`: https://github.com/wnfs-wg/rs-wnfs

### Impact

For example, easier setup of projects that expose Rust bindings, or a Rust implementation, for some larger non-Rust system.

## Solution

Support overriding the repo name when running the template.

**Comment by zeeshanlakhani** [comment]
Yep. I thought it may be an unnecessary step, but I see the benefit.
