### ISSUE TITLE
use of undeclared crate or module `proptest`

### ISSUE THREAD

**Issue by QuinnWilton** [fission-codes/rust-template#33]
# Summary

## Problem

Running `cargo test` fails with the following:

```
error[E0433]: failed to resolve: use of undeclared crate or module `proptest`
 --> rhizome/src/test_utils/rvg.rs:1:5
  |
1 | use proptest::{
  |     ^^^^^^^^ use of undeclared crate or module `proptest`
```

This happens because `proptest` is an optional dependency, and only installed when the `test_utils` feature is enabled.

### Impact

I'm unable to run tests locally without manually specifying the feature each time.

## Solution

Since there's no way to enable this feature for the `test` profile, `proptest` should be unconditionally installed as part of the `dev-dependencies`:

```
[dev-dependencies]
proptest = { version = "1.0" }
```

**Comment by zeeshanlakhani** [comment]
Good catch. I had some intentions before this on how to push for certain feature flags, but going simple is better here.
