### ISSUE TITLE
workspace Support

### ISSUE THREAD

**Issue by pinkforest** [fission-codes/rust-template#55]
Usually I do workspace configuration and put crates in crates/* whilst the github repo acts as a monorepo for these

Large projects tend to divide and layer things between small crates that can be re-used across various projects

**Comment by zeeshanlakhani** [comment]
@pinkforest so, the rust+wasm template generator does break up things as a workspace. I just take the approach of https://github.com/tokio-rs/tokio (which I prefer, and do not use a `crates` folder specifically). Do you mean, more so, having a prompt for the workspace or not for the rust-only generator, which doesn't have that option today?
