### ISSUE TITLE
Release profiles

### ISSUE THREAD

**Issue by pinkforest** [fission-codes/rust-template#61]
Some people might want reduced codesize e.g. strip symbols e.g.: workspace Cargo.toml

```toml
[profile.release]
codegen-units = 1
strip = "symbols"
debug = false
lto = true
opt-level = "z"
panic = 'abort'
```

It would be nice to have `#` and comment what they do / e.g. leave as pointers to set / forget / remove

**Comment by zeeshanlakhani** [comment]
I did add this for the wasm package. But, agree, this could be a nice commented-out piece in the rust generator.
