### ISSUE TITLE
Unsafe code policy

### ISSUE THREAD

**Issue by pinkforest** [fission-codes/rust-template#63]
- `#![forbid(unsafe_code)]` or use `deny` + `allow` explicitly in places if really must given:
- Unsafe should be documented: https://doc.rust-lang.org/std/keyword.unsafe.html
- clippy has a usable lint for deny undocumented unsafe blocks
- Difference between unsafe behind a safe fn (soundness issues) and unsafe behind unsafe fn
- Pointer to wg-unsafe-code-guidelines: https://github.com/rust-lang/unsafe-code-guidelines
- `cargo-geiger` your deps - `cargo-vet` is on-going work also
- `unsafe` should be justified with benchmarks if it's performance issue driven
- Merge policy for unsafe could be 2x reviewers  perhaps
- https://www.reddit.com/r/rust/comments/y1u068/the_stigma_around_unsafe/
- https://youtu.be/QAz-maaH0KM
- https://github.com/rust-secure-code/safety-dance

**Comment by zeeshanlakhani** [comment]
I think forbid may be too strong (was reading through https://github.com/bevyengine/bevy/issues/3824). I do think this could be a prompt. Forbid unsafe code? If so you get the macro and policy in the readme.
